### ISSUE TITLE
How to show the ViewController in a UIView?

### ISSUE THREAD

**Issue by thechaudharysab** [ermalkaleci/CarbonKit#186]
I have a header and footer which is static for all the view controllers as shown in this image below.
<img width="321" alt="screen shot 2017-10-05 at 3 57 12 pm" src="https://user-images.githubusercontent.com/6399152/31224111-01a391be-a9e6-11e7-8c46-490542c00ad2.png">
So in this white area I want to show the viewcontrollers that I've made. How can I do that with CarbonKit?

**Comment by thechaudharysab** [comment]
carbonTabSwipeNavigation.insert(intoRootViewController: self, andTargetView: *YOUR_UIVIEW)

**Comment by kristiyandobrev** [comment]
@thechaudharysab . That crashes On `iOS 11` and `XCode 9`:

`2017-10-05 14:02:28.464731+0200 TrackunitOn[92659:2476568] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MyApp.SomeViewController carbonTabSwipeNavigation:viewControllerAtIndex:]: unrecognized selector sent to instance 0x7b6400004600'`
